apiVersion: v1
kind: Service
metadata:
  name: {{ include "roast-co.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "roast-co.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "roast-co.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP