apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret
  namespace: dev
spec:
  provider: aws
  parameters:
    region: eu-central-1
    usePodIdentity: "true"
    objects: |
      - objectName: roast-co-dev-rds-credentials
        objectType: secretsmanager
        jmesPath:
          - path: DATABASE_URL
            objectAlias: DATABASE_URL